language: java
sudo: false

matrix:
  include:
    #==============================
    #
    #     osx 
    #
    #==============================

    - os: osx
      compiler: javac
      osx_image: xcode7.3

    - os: osx
      compiler: javac
      osx_image: xcode8

    - os: osx
      compiler: javac
      osx_image: xcode8.3

    - os: osx
      compiler: javac
      osx_image: xcode9

    - os: osx
      compiler: javac
      osx_image: xcode9.1

    - os: osx
      compiler: javac
      osx_image: xcode9.2

    - os: osx
      compiler: javac
      osx_image: xcode9.3

    - os: osx
      compiler: javac
      osx_image: xcode9.4

    - os: osx
      compiler: javac
      osx_image: xcode10

    #==============================
    #
    #     linux 
    #
    #==============================
    
    - os: linux
      compiler: javac

before_install:
  - eval

before_script:
  - mkdir build

script:
  - javac GENOME/src/Utils/*.java -d build -cp build
  - javac GENOME/src/Manager/*.java -d build -cp build
  - javac GENOME/src/Exception/*.java -d build -cp build
  - javac GENOME/src/Json/*.java -d build -cp build
  - javac GENOME/src/GUI/*.java -d build -cp build
  - javac GENOME/src/Download/*.java -d build -cp build
  - javac GENOME/src/Data/*.java -d build -cp build
  - javac GENOME/src/Excel/*.java -d build -cp build:GENOME/lib/poi-3.17/poi-3.17.jar:GENOME/lib/poi-3.17/poi-examples-3.17.jar:GENOME/lib/poi-3.17/poi-excelant-3.17.jar:GENOME/lib/poi-3.17/poi-ooxml-3.17.jar:GENOME/lib/poi-3.17/poi-ooxml-schemas-3.17.jar:GENOME/lib/poi-3.17/poi-scratchpad-3.17.jar:GENOME/lib/poi-3.17/lib/commons-codec-1.10.jar:GENOME/lib/poi-3.17/lib/commons-collections4-4.1.jar:GENOME/lib/poi-3.17/lib/commons-logging-1.2.jar:GENOME/lib/poi-3.17/lib/junit-4.12.jar:GENOME/lib/poi-3.17/lib/log4j-1.2.17.jar:GENOME/lib/poi-3.17/ooxml-lib/ooxml-lib:GENOME/lib/poi-3.17/ooxml-lib/curvesapi-1.04.jar:GENOME/lib/poi-3.17/ooxml-lib/xmlbeans-2.6.0.jar
  - javac GENOME/src/Main/*.java -d build -cp build